package com.niyuj.group.controller;

import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class LoginController {
	@Autowired
UserMap user_map;
	@PostMapping("/api/login")
	public String welcomeapi(@RequestBody String username) {

		System.out.println(username);
		String loginMessage=user_map.login(username);
		UUID uuid = UUID.randomUUID();
		 String uuidAsString = uuid.toString();//Token getting generated by uuid and stored as string
		return loginMessage+" "+"Your token for this session is"+" "+uuidAsString;
	}
}
